import type { Announcement, Certificate, Member, Workshop } from "@/lib/types";

export const members: Member[] = [
  {
    id: "m-001",
    name: "Aina Rahman",
    role: "delegate",
    city: "Kota Kinabalu",
    country: "Malaysia",
    specialty: "Hospital clowning",
    avatar: "AR",
    delegateId: "BICC26-0182",
    bio: "Community performer focused on gentle interactive routines.",
  },
  {
    id: "m-002",
    name: "Marco Silva",
    role: "mentor",
    city: "Lisbon",
    country: "Portugal",
    specialty: "Physical comedy",
    avatar: "MS",
    delegateId: "BICC26-M014",
    bio: "Movement coach and mentor for stage timing.",
  },
  {
    id: "m-003",
    name: "Lina Chen",
    role: "verified_performer",
    city: "Singapore",
    country: "Singapore",
    specialty: "Balloon theatre",
    avatar: "LC",
    delegateId: "BICC26-0207",
    bio: "Creates compact visual stories for family audiences.",
  },
  {
    id: "m-004",
    name: "Datu Amir",
    role: "hub_member",
    city: "Tawau",
    country: "Malaysia",
    specialty: "Juggling",
    avatar: "DA",
    bio: "New hub member exploring workshop options.",
  },
  {
    id: "m-005",
    name: "Admin Team",
    role: "admin",
    city: "Tawau",
    country: "Malaysia",
    specialty: "Convention operations",
    avatar: "BT",
    delegateId: "BICC26-ADMIN",
    bio: "BICC registration and workshop operations.",
  },
];

export const workshops: Workshop[] = [
  {
    id: "11111111-1111-4111-8111-111111111101",
    title: "Expressive Entrances",
    mentorId: "m-002",
    mentorName: "Marco Silva",
    track: "Stagecraft",
    time: "Mon 10:00 AM",
    room: "Studio Red",
    capacity: 24,
    registered: 18,
    preview: "Build a strong first thirty seconds with movement, silence, and focus.",
  },
  {
    id: "11111111-1111-4111-8111-111111111102",
    title: "Gentle Comedy in Care Spaces",
    mentorId: "m-001",
    mentorName: "Aina Rahman",
    track: "Outreach",
    time: "Mon 2:00 PM",
    room: "Studio Teal",
    capacity: 18,
    registered: 16,
    preview: "A practical session for consent-led clowning in hospitals and shelters.",
  },
  {
    id: "11111111-1111-4111-8111-111111111103",
    title: "Balloon Character Lab",
    mentorId: "m-003",
    mentorName: "Lina Chen",
    track: "Props",
    time: "Tue 11:30 AM",
    room: "Workshop Hall",
    capacity: 30,
    registered: 21,
    preview: "Turn simple balloon forms into readable characters and quick stories.",
  },
  {
    id: "11111111-1111-4111-8111-111111111104",
    title: "Performer Portfolio Clinic",
    mentorId: "m-002",
    mentorName: "Marco Silva",
    track: "Career",
    time: "Wed 9:30 AM",
    room: "Mentor Lounge",
    capacity: 12,
    registered: 9,
    preview: "Small-group feedback for bios, show blurbs, and performance submissions.",
  },
];

export const announcements: Announcement[] = [
  {
    id: "a-001",
    title: "Delegate check-in opens",
    body: "Digital pass check-in is available from 8:00 AM at the convention desk.",
    audience: "delegates",
    date: "2026-08-17",
  },
  {
    id: "a-002",
    title: "Outreach signup live",
    body: "Delegates can now join the community outreach visit shortlist.",
    audience: "delegates",
    date: "2026-08-18",
  },
  {
    id: "a-003",
    title: "Free hub is open",
    body: "Browse previews, meet members, and upgrade when you are ready for full access.",
    audience: "members",
    date: "2026-08-01",
  },
];

export const certificates: Certificate[] = [
  {
    id: "c-001",
    title: "BICC 2026 Delegate Participation",
    issuedTo: "Aina Rahman",
    status: "Ready",
    issuedDate: "2026-08-21",
  },
  {
    id: "c-002",
    title: "Outreach Performer Recognition",
    issuedTo: "Aina Rahman",
    status: "Pending",
    issuedDate: "2026-08-21",
  },
];
